alter table PROPOSALS_PROPOSAL alter column RESPONSIBLE_ID rename to RESPONSIBLE_ID__U17158 ^
alter table PROPOSALS_PROPOSAL alter column RESPONSIBLE_ID__U17158 set null ;
alter table PROPOSALS_PROPOSAL drop constraint FK_PROPOSALS_PROPOSAL_ON_RESPONSIBLE ;
drop index IDX_PROPOSALS_PROPOSAL_ON_RESPONSIBLE ;
